version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    image: boilerplate-express
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - boilerplate

networks:
  boilerplate: